name: Build librespot

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: librespot-org/librespot
          # ref را کاملاً حذف می‌کنیم تا خودش از شاخه پیش‌فرض استفاده کند
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release --no-default-features --features portaudio-backend

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: librespot-macos
          path: target/release/librespot
