name: Build Librespot
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      # اضافه کردن این بخش برای تنظیم هدف روی نسخه قدیمی
      - name: Build
        run: |
          export MACOSX_DEPLOYMENT_TARGET=10.12
          cargo build --release --no-default-features --features portaudio-backend,rustls-tls-webpki-roots
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: librespot-macos
          path: target/release/librespot
