name: Build MacOS
on: [push]

jobs:
  build:
    runs-on: macos-12  # استفاده از نسخه کمی قدیمی‌تر
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0 # نسخه پایدار و سازگار
          override: true
      
      - name: Build
        run: |
          # تنظیم فلگ برای سازگاری با معماری Core 2 Duo
          export MACOSX_DEPLOYMENT_TARGET=10.12
          cargo build --release --features="daemon"
          
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: spotify-player-macos
          path: target/release/spotify-player
